version: '3.8'

services:
  vrp:
    image: nvidia/cuda:11.3.1-devel-ubuntu20.04
    container_name: vrp_container
    runtime: nvidia
    volumes:
      - .:/app
    working_dir: /app
    command: >
      /bin/bash -c "
      apt-get update && 
      apt-get install -y build-essential cmake && 
      cmake . && 
      make && 
      ./main"
