version: '3.8'

services:
  vrp:
    image: nvidia/cuda:11.3.1-devel-ubuntu20.04
    container_name: vrp_container
    runtime: nvidia
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: >
      /bin/bash -c "
      apt-get update &&
      apt-get install -y build-essential cmake cuda-toolkit-11-3 &&
      # Vérifie la présence de Thrust pour s'assurer qu'il est installé
      if [ -f /usr/local/cuda/include/thrust/device_vector.h ]; then echo 'Thrust is installed'; else echo 'Thrust is missing'; exit 1; fi &&
      cmake . &&
      make &&
      ./main"
